In [153]:
def dy_dx(x):
    return 2*x

In [154]:
import math
def dy_dx(x):
    return math.cosl(x)


## Autograd

Autograd is a core componenet of PyTorch that provides automatic differentiation for tensor opetations. it eables gradient computation, which is essential for training machine learning models using optimization algorighms like gradient descent

In [155]:
import torch

In [156]:
x = torch.tensor(3.0, requires_grad=True)

In [157]:
y = x**2


In [158]:
x

tensor(3., requires_grad=True)

In [159]:
y

tensor(9., grad_fn=<PowBackward0>)

In [160]:
y.backward()

In [161]:
x.grad

tensor(6.)

In [162]:
y = x**2
y.retain_grad()
z = torch.sin(y)


In [163]:
z.backward()

In [164]:
y.grad

tensor(-0.9111)

In [165]:
x.grad

tensor(0.5332)

In [166]:
z 

tensor(0.4121, grad_fn=<SinBackward0>)

In [167]:
import torch

x = torch.tensor([7.0])
y = torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [168]:
def binary_cross_entropy(prediction, target):
    epsilon = 1e-8
    prediction = torch.clamp(prediction, epsilon, 1-epsilon)
    return -((target * torch.log(prediction)) + (1 - target) * torch.log(1 - prediction))

In [169]:
z = w * x + b
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy(y_pred, y)

In [170]:
print(loss)

tensor([7.0010])


In [171]:
dloss_dy_pred = (y_pred - y)/ (y_pred * (1 - y_pred))
dy_pred_dz = y_pred * (1 - y_pred)
dz_dw = x
dz_db = 1

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [172]:
print(f"Manual Gradient of loss w.r.t weight (dw):{dL_dw}")
print(f'Manual Gradient of loss w.r.t bias (db):{dL_db}')

Manual Gradient of loss w.r.t weight (dw):tensor([6.9936])
Manual Gradient of loss w.r.t bias (db):tensor([0.9991])


In [173]:
from torch.jit import TracedModule
x = torch.tensor(7.0)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad= True)
b = torch.tensor(0.0, requires_grad=True)

In [174]:
z = w* x + b
y_pred = torch.sigmoid(z)
y_pred



tensor(0.9991, grad_fn=<SigmoidBackward0>)

In [175]:
loss = binary_cross_entropy(y_pred, y)
loss

tensor(7.0010, grad_fn=<NegBackward0>)

In [176]:
loss.backward()

In [177]:
print(w.grad)
print(b.grad)

tensor(6.9936)
tensor(0.9991)


In [178]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [191]:
y = (x**2).mean()
y


tensor(4.6667, grad_fn=<MeanBackward0>)

In [192]:
y.backward()



In [193]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [194]:
x.grad.zero_()


tensor([0., 0., 0.])

In [195]:
x.requires_grad_(False)

tensor([1., 2., 3.])

In [196]:
x


tensor([1., 2., 3.])

In [197]:
y = x**2

In [198]:
y

tensor([1., 4., 9.])

In [199]:
x = torch.tensor(2.0, requires_grad=True)


In [200]:
z = x.detach()
z

tensor(2.)

In [201]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [205]:
y1 = z**2

In [206]:
y1

tensor(4.)

In [208]:
with torch.no_grad():
    y = x**2
    