In [9]:
import torch
import torch.nn as nn 

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmod = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmod(out)
        return out

In [10]:
features = torch.rand(10, 5)
model = Model(features.shape[1])

model(features)

tensor([[0.5259],
        [0.5068],
        [0.5125],
        [0.4830],
        [0.5111],
        [0.4333],
        [0.5090],
        [0.4562],
        [0.5101],
        [0.4786]], grad_fn=<SigmoidBackward0>)

In [11]:
model.linear.weight

Parameter containing:
tensor([[-0.1367,  0.2506,  0.0683, -0.3367,  0.4289]], requires_grad=True)

In [12]:
model.linear.bias

Parameter containing:
tensor([-0.2091], requires_grad=True)

In [14]:
from torchinfo import summary

summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [21]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [22]:
features = torch.rand(10, 5)

model = Model(features.shape[1])
model(features)

tensor([[0.6344],
        [0.6564],
        [0.6508],
        [0.6680],
        [0.6636],
        [0.6660],
        [0.6392],
        [0.6267],
        [0.6610],
        [0.6527]], grad_fn=<SigmoidBackward0>)

In [24]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [37]:
loss_func = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.05)

In [35]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(), 
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        
    def forward(self, features):
        out = self.network(features)
        return out

    def loss_function(self, y_pred, y):
        loss = loss_func(y_pred, y)
        return loss

In [33]:
features = torch.rand(10, 5)
model = Model(features.shape[1])
model(features)

tensor([[0.4968],
        [0.4997],
        [0.4961],
        [0.5000],
        [0.5000],
        [0.4869],
        [0.5000],
        [0.4980],
        [0.4970],
        [0.5000]], grad_fn=<SigmoidBackward0>)