In [2]:
import torch 
print(torch.__version__)

2.11.0+cpu


## Tensors

In [3]:
a = torch.empty(2,3)

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.3809, 0.9004, 0.6576],
        [0.9702, 0.7916, 0.6878]])

In [8]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.Tensor([[1,2], [2,3]])

tensor([[1., 2.],
        [2., 3.]])

In [11]:
print('using arange-> ', torch.arange(0,10,2))
print('using linspace -> ', torch.linspace(0,10,10))
print('using eye -> ', torch.eye(5))
print('using full-> ', torch.full((3,3), 5))

using arange->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [12]:
x = torch.tensor([[1, 2,3], [2, 3,4 ]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

## Tensor Data type

In [17]:
x.dtype

torch.int64

In [18]:
torch.tensor([1.2, 2.3, 4.4], dtype = torch.float64)

tensor([1.2000, 2.3000, 4.4000], dtype=torch.float64)

In [19]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)

## Mathematical Operations

In [20]:
x = torch.rand(2,2)

In [21]:
x + 2
x-2
x*3
x/3
x* 100
(x* 100)//3
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

In [22]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [23]:
print(f'a+b = {a+b}')
print(f'a-b = {a-b}')
print(f'a*b = {a*b}')

a+b = tensor([[1.1186, 1.4921, 0.9357],
        [1.0899, 0.5967, 1.7253]])
a-b = tensor([[-0.8752, -0.0209,  0.4879],
        [ 0.4852,  0.2399,  0.0776]])
a*b = tensor([[0.1213, 0.5565, 0.1594],
        [0.2381, 0.0746, 0.7426]])


In [24]:
torch.ceil(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [25]:
torch.sum(b, dim = 0)

tensor([1.2992, 0.9349, 1.0477])

In [26]:
torch.sum(b, dim = 1)

tensor([1.9773, 1.3046])

In [27]:
torch.median(a)

tensor(0.7118)

In [28]:
torch.prod(a)

tensor(0.0189)

In [29]:
torch.std(a)

tensor(0.2890)

In [30]:
torch.var(a)

tensor(0.0835)

In [31]:
torch.argmax(a)

tensor(5)

In [32]:
torch.argmin(b)

tensor(4)

## matrix operation

In [33]:
f = torch.Tensor([[1,2,4], [2,3, 4]])

In [34]:
 torch.transpose(f, 0, 1)

tensor([[1., 2.],
        [2., 3.],
        [4., 4.]])

In [35]:
torch.log(f)

tensor([[0.0000, 0.6931, 1.3863],
        [0.6931, 1.0986, 1.3863]])

In [36]:
a = torch.tensor([1,2,3], dtype = torch.float64)
b = torch.tensor([2,3,4], dtype = torch.float64)

torch.dot(a, b)

tensor(20., dtype=torch.float64)

In [37]:
torch.exp(a)

torch.log(b)

tensor([0.6931, 1.0986, 1.3863], dtype=torch.float64)

In [38]:
torch.sqrt(a)

tensor([1.0000, 1.4142, 1.7321], dtype=torch.float64)

In [39]:
torch.sigmoid(a)

tensor([0.7311, 0.8808, 0.9526], dtype=torch.float64)

In [40]:
torch.softmax(a, dim=0)

tensor([0.0900, 0.2447, 0.6652], dtype=torch.float64)

torch.relu(a)

## Inplace Operations

In [41]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m+n)

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])


In [42]:
m.add_(n)

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [43]:
m 

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [45]:
torch.relu(m)

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [46]:
m.relu_()

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [47]:
m

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

## Copying a Tensor

In [48]:
a = torch.rand(2,3)
a

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [49]:
b = a

In [50]:
b

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [51]:
a[0][0] = 0

In [54]:
a

tensor([[0.0000, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [55]:
b

tensor([[0.0000, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [56]:
id(a)

2116939077328

In [58]:
id(b)

2116939077328

In [59]:
b = a.clone()

In [60]:
a[0][0]  = 1

In [61]:
a 

tensor([[1.0000, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [62]:
b

tensor([[0.0000, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [64]:
torch.cuda.is_available()

False

## Reshaping Tensors


In [65]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [67]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
b = torch.rand(2,3,4)
b

tensor([[[0.7668, 0.1659, 0.4393, 0.2243],
         [0.8935, 0.0497, 0.1780, 0.3011],
         [0.1893, 0.9186, 0.2131, 0.3957]],

        [[0.6017, 0.4234, 0.5224, 0.4175],
         [0.0340, 0.9157, 0.3079, 0.6269],
         [0.8277, 0.6594, 0.0887, 0.4890]]])

In [73]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [76]:
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [77]:
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch

In [78]:
import numpy as np

In [79]:
a = torch.tensor([1,2,3])


In [82]:
b = a.numpy()
b

array([1, 2, 3])

In [83]:
type(b)

numpy.ndarray

In [84]:
c = np.array([1,2,3])

In [85]:
torch.from_numpy(c)

tensor([1, 2, 3])