In [29]:
import torch 
import numpy as np 

## Tersors 

In [30]:
array = np.array([[1,2,3], [2,3,4]])
array 

array([[1, 2, 3],
       [2, 3, 4]])

In [31]:
tensor =torch.Tensor([[1,2,3], [1,2,3]])
tensor

tensor([[1., 2., 3.],
        [1., 2., 3.]])

In [32]:
tensor * 3

tensor([[3., 6., 9.],
        [3., 6., 9.]])

In [33]:
tensor.sum()

tensor(12.)

In [34]:
torch.ones((2,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
torch.rand((2,4))

tensor([[0.0722, 0.7410, 0.4767, 0.2512],
        [0.6996, 0.4739, 0.6225, 0.1359]])

In [36]:
tensor.shape

torch.Size([2, 3])

In [37]:
tensor.dtype

torch.float32

## Differentiation


In [38]:
a = torch.tensor([2., 3.], requires_grad = True)
b = torch.tensor([6., 4.], requires_grad = True)

f = 3 * a**3 - b**2

$$f = 3  a^3 - b^2$$

In [39]:
f 

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [40]:
f.backward(gradient = torch.tensor([1,1]))

In [41]:
print(a.grad)

tensor([36., 81.])


In [ ]:
9 * a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

In [43]:
print(b.grad)

tensor([-12.,  -8.])


In [44]:
- 2 * b

tensor([-12.,  -8.], grad_fn=<MulBackward0>)

## Neural Networks 

In [50]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim 
from torch.utils.data import DataLoader, TensorDataset

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [51]:
X, y = load_breast_cancer(return_X_y= True)
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.2)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

In [ ]:
X_train_scaled_tensor = torch.from_numpy(X_train_scaled).float()
X_test

array([[-0.47133211, -0.48352345, -0.47570752, ..., -0.14690233,
         0.20519727, -0.39883962],
       [ 1.16864407,  0.12994516,  1.13698885, ...,  1.18901492,
         0.25002952, -0.01549422],
       [-0.67845713, -1.23944545, -0.73151453, ..., -0.48734085,
         0.31087329, -0.92641399],
       ...,
       [ 0.9473324 ,  1.20983373,  0.99281421, ...,  0.86833399,
        -1.19581049,  0.48984937],
       [ 1.4949369 , -0.28362919,  1.45005379, ...,  1.67535567,
         1.09383648, -0.33052064],
       [ 2.12198662,  0.65840127,  2.15856918, ...,  1.93372419,
         1.47491059,  0.90735427]], shape=(455, 30))