# TensorFlow Deep Learning

This notebook covers basic deep learning tasks using TensorFlow, including image classification and regression.

## 1. MNIST Handwritten Digit Classification

In [31]:
import tensorflow as tf

### Load and Normalize MNIST Data

In [32]:
mnist = tf.keras.datasets.mnist

(X_train, y_train) , (X_test , y_test) = mnist.load_data()

In [33]:
X_train.shape

(60000, 28, 28)

In [34]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [35]:
X_train, X_test = X_train/ 255.0, X_test/255.0

In [36]:
y_train

array([5, 0, 4, ..., 5, 6, 8], shape=(60000,), dtype=uint8)

### Build the Model

In [44]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,  Flatten , Input, Dropout

model = Sequential()
model.add(Input((28,28)) )
model.add(Flatten())
model.add(Dense(128,activation ='relu'))
model.add(Dropout(0.2))
model.add(Dense(10))

### Test with Untrained Model

In [45]:
nonsense_prediction = model(X_train[:1]).numpy()
nonsense_prediction

array([[ 0.07228943, -0.18293992, -0.78334063,  0.5427401 ,  0.4151761 ,
        -0.27232286,  0.29072225,  0.04306351,  0.02320868, -0.6838139 ]],
      dtype=float32)

In [46]:
tf.nn.softmax(nonsense_prediction).numpy().sum()


np.float32(1.0)

### Compile and Train

In [47]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

loss_fn = SparseCategoricalCrossentropy(from_logits= True)

# -tf.math.log(1/10)
loss_fn(y_train[:1], nonsense_prediction)

<tf.Tensor: shape=(), dtype=float32, numpy=2.601665496826172>

In [48]:
from tensorflow.keras.optimizers import Adam
optimizer = Adam(learning_rate = 0.01)
model.compile(optimizer= optimizer, loss = loss_fn, metrics = ['accuracy'])

In [49]:
model.fit(X_train, y_train, epochs = 10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9058 - loss: 0.3177
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9327 - loss: 0.2413
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9383 - loss: 0.2284
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9444 - loss: 0.2139
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9470 - loss: 0.2013
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9496 - loss: 0.1966
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9498 - loss: 0.1986
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9521 - loss: 0.1988
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9538 - loss: 0.1812
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9550 - loss: 0.1798


### Evaluate the Model

In [50]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9645 - loss: 0.2066


[0.20658698678016663, 0.9645000100135803]

In [53]:
tf.argmax(tf.nn.softmax(model(X_train[:1])).numpy(), axis = 1)

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([5])>

## 2. California Housing Regression

In [83]:
import pandas as pd

### Load Housing Data

In [84]:
df = pd.read_csv('housing.csv')
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847


### Train-Test Split and Scaling

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

X , y = df.drop('MedHouseVal', axis = 1), df['MedHouseVal']
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.2, random_state=42)

In [86]:
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

In [87]:
X_train_scaled.shape

(16512, 8)

### Build Regression Model

In [88]:
model = Sequential()
model.add(Input((8,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))

### Compile and Train

In [89]:
model.compile(optimizer= 'adam', loss = 'mse', metrics = ['mae', 'r2_score'])

In [90]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10


516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.7024 - mae: 0.5759 - r2_score: 0.4745
Epoch 2/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4103 - mae: 0.4464 - r2_score: 0.6931
Epoch 3/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3615 - mae: 0.4245 - r2_score: 0.7296
Epoch 4/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3492 - mae: 0.4153 - r2_score: 0.7388
Epoch 5/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3336 - mae: 0.4055 - r2_score: 0.7504
Epoch 6/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3285 - mae: 0.4009 - r2_score: 0.7542
Epoch 7/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3161 - mae: 0.3916 - r2_score: 0.7635
Epoch 8/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3082 - mae: 0.3861 - r2_score: 0.7694
Epoch 9/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3083 - mae: 0.3839 - r2_score: 0.7694
Epoch 10/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2951 - mae: 0.3747 - r2_score: 0.7792


### Evaluate Regression Model

In [91]:
model.evaluate(X_test_scaled, y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3138 - mae: 0.3940 - r2_score: 0.7605


[0.3138088583946228, 0.3939552307128906, 0.7605259418487549]

In [93]:
df.MedHouseVal.describe()

count    20640.000000
mean         2.068558
std          1.153956
min          0.149990
25%          1.196000
50%          1.797000
75%          2.647250
max          5.000010
Name: MedHouseVal, dtype: float64